[package]
name = "toml_test_suite"
version = "0.0.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
publish = false
edition = "2018"

[dev-dependencies]
toml = { path = ".." }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
